Repository DongSanOfficial/DongSan-Front, pull requests merged in 2024-12, with the labels that each got.

#23 [DF-46] 사용자 위치 트래킹 및 폴리라인 그리기 구현
  src/assets/images/loginGoogle.png
  src/assets/images/loginKakao.png
  src/components/Map.tsx
  src/components/bottomsheet/BottomSheet.tsx
  src/components/map/MainMap.tsx
  src/components/map/TrackingMap.tsx
  src/pages/main/components/PathCard.tsx
  src/pages/main/index.tsx
  src/pages/newway/index.tsx
  src/styles/GlobalStyles.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#25 [DF-51]산책로 이용하기 페이지
  src/navigator/routes.tsx
  src/pages/usingtrail/index.tsx
  src/styles/BottomBarLayout.tsx
Labels: 💎UI 개발

#26 [DF-52] 이용한 산책로 상세 페이지 구현
  src/components/newway_register/DateDisplay.tsx
  src/components/newway_register/ToggleSwitch.tsx
  src/components/newway_register/TrailInfo.tsx
  src/navigator/routes.tsx
  src/pages/review/index.tsx
  src/pages/usingtrail/detail_using.tsx
Labels: 💎UI 개발, 🚧 리팩토링

#28 [DF-52] 특정 화면에서 레이아웃 깨지는 현상 수정
  src/components/newway_register/TrailInfo.tsx
  src/pages/newway/index.tsx
  src/pages/usingtrail/detail_using.tsx
  src/pages/usingtrail/index.tsx
Labels: 🐞 버그, 🚧 리팩토링

#27 [DF-43] 로컬스토리지에서 쿠키로 토큰 변경
  src/pages/review/index.tsx
Labels: 🐞 버그
