Repository DongSanOfficial/DongSan-Front, pull requests merged in 2025-03, with the labels that each got.

#88 [DF-70]산책로 저장 및 삭제 구현
  src/components/bottomsheet/BookmarkContent.tsx
  src/pages/detail/index.tsx
Labels: 🐞 버그

#90 [DF-92] [QA] 북마크 ui 리팩토링, 수정사항 자동 업데이트, 중복 이름 처리
  src/apis/bookmark.ts
  src/components/bottomsheet/BottomSheetStorage.tsx
  src/components/map/MainMap.tsx
  src/components/map/PathMap.tsx
  src/navigator/routes.tsx
  src/pages/detail/bookmark/components/BookmarkContent.tsx
  src/pages/detail/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/bookmark/TrailBookmark.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/review/ReviewableHistory.tsx
  src/pages/mypage/review/TrailReviewPage.tsx
  src/pages/mypage/trailList/TrailListPage.tsx
  src/pages/newway/index.tsx
  src/pages/newway/registration.tsx
  src/pages/test/index.tsx
Labels: 🐞 버그, 💎UI 개발, 🚧 리팩토링

#92 [DF-100] 여러 개의 토스트 컴포넌트가 동시에 표시되는 문제 해결
  src/components/toast/ToastComponent.tsx
  src/context/ToastContext.tsx
Labels: 🐞 버그, 🚧 리팩토링

#93 [DF-101] 산책로 검색 및 조회 페이지 ui/ux 개선
  src/components/bottomsheet/BottomSheet.tsx
  src/components/map/CourseImage.tsx
  src/pages/main/components/PathCard.tsx
  src/pages/main/index.tsx
  src/pages/mypage/review/ReviewableHistory.tsx
  src/pages/mypage/review/TrailReviewPage.tsx
Labels: 💎UI 개발, 🚧 리팩토링

#94 [DF-97] 산책로 삭제 기능 구현
  src/apis/walkway.ts
  src/components/modal/ConfirmationModal.tsx
  src/components/newway_register/InputField.tsx
  src/pages/detail/index.tsx
  src/pages/error/locationAcceptance.tsx
  src/pages/review/index.tsx
  src/styles/colors/theme.ts
Labels: ⚙ 기능개발
