Repository DongSanOfficial/DongSan-Front, pull requests merged in 2025-02, with the labels that each got.

#52 [DF-47] 산책로 등록 api 연동
  src/App.tsx
  src/apis/walkway.ts
  src/apis/walkway.type.ts
  src/components/modal/ConfirmationModal.tsx
  src/components/toast/toast.tsx
  src/context/ToastContext.tsx
  src/hooks/useToast.ts
  src/index.tsx
  src/pages/main/components/PathCard.tsx
  src/pages/main/index.tsx
  src/pages/newway/NewwayTest.tsx
  src/pages/newway/registration.tsx
  src/pages/splash/index.tsx
  src/types/.gitkeep
  src/types/toast.type.ts
  src/utils/drawPathUtils.ts
Labels: ⚙ 기능개발, 💎UI 개발

#53 산책로 리뷰 내용보기 api 수정
  src/apis/review.ts
  src/pages/review/ReviewCheck.tsx
  src/pages/review/index.tsx
  src/pages/splash/index.tsx
Labels: 🐞 버그, ⚙ 기능개발

#56 [DF-83] 토큰 재발급 api 연동
  src/App.tsx
  src/apis/auth.ts
  src/apis/auth.type.ts
  src/apis/instance.ts
  src/assets/svg/SplashLogo.svg
  src/components/SplashScreen.tsx
  src/index.tsx
  src/navigator/routes.tsx
  src/pages/mypage/TrailListPage.tsx
  src/pages/signin/index.tsx
  src/pages/splash/index.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#57 [DF-63]산책로 리뷰보기 api수정
  src/apis/review.ts
  src/apis/review.type.ts
  src/components/TrailCardAll_View.tsx
  src/components/TrailReviewCard.tsx
  src/components/review/starCount.tsx
  src/pages/detail/index.tsx
  src/pages/review/ReviewCheck.tsx
  src/pages/review/index.tsx
Labels: 💎UI 개발, 🚧 리팩토링

#59 hotfix: 별 컴포넌트 위치이동
  src/components/review/starCount.tsx
Labels: 🐞 버그

#60 [DF-85] 토큰 갱신 상태 관리 추가
  src/apis/instance.ts
  src/pages/mypage/index.tsx
Labels: 🐞 버그

#62 [DF-89] 거리 측정 로직 수정(m, km)
  src/components/newway_register/TrailInfo.tsx
  src/pages/newway/index.tsx
  src/pages/newway/registration.tsx
  src/utils/calculateDistance.ts
Labels: 🐞 버그

#64 Feat/df 84/inquire review page
  src/apis/review.ts
  src/apis/review.type.ts
  src/components/HistoryCardAll_View.tsx
  src/components/HistoryCard_mp.tsx
  src/components/ReviewCard_mp.tsx
  src/navigator/routes.tsx
  src/pages/mypage/ReviewableHistory.tsx
  src/pages/mypage/TrailReviewPage.tsx
  src/pages/mypage/index.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#66 hotfix(DF-84): 산책기록 state넘기기 수정
  src/apis/review.ts
  src/pages/mypage/index.tsx
  src/pages/review/index.tsx
Labels: 🐞 버그

#69 [DF-86] 가이드 페이지 구현
  package-lock.json
  package.json
  src/assets/images/guide/card.png
  src/assets/images/guide/cardImage.png
  src/assets/images/guide/follow.png
  src/assets/images/guide/home.png
  src/assets/images/guide/mypage.png
  src/assets/images/guide/newway.png
  src/assets/images/guide/newwayGuide.png
  src/components/button/GuideButton.tsx
  src/navigator/routes.tsx
  src/pages/guide/index.tsx
  src/pages/guide/sections/FollowGuideSection.tsx
  src/pages/guide/sections/MyPageSection.tsx
  src/pages/guide/sections/RegisterSection.tsx
  src/pages/guide/sections/SearchSection.tsx
  src/pages/guide/sections/WalkingMethodSection.tsx
  src/pages/guide/styles/CommonStyles.ts
  src/pages/main/header/components/SearchInput.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
  yarn.lock
Labels: ⚙ 기능개발, 💎UI 개발

#70 [DF-77] 로딩 스피너 제작
  src/components/loading/LoadingSpinner.tsx
  src/pages/mypage/ReviewableHistory.tsx
  src/pages/mypage/TrailListPage.tsx
  src/pages/mypage/TrailReviewPage.tsx
  src/pages/mypage/index.tsx
  src/pages/review/ReviewCheck.tsx
  yarn.lock
Labels: 💎UI 개발

#71 [DF-84]리뷰가능한 산책로 목록페이지 api연동
  src/apis/review.ts
  src/pages/mypage/ReviewableHistory.tsx
  src/pages/mypage/TrailReviewPage.tsx
  src/pages/mypage/index.tsx
Labels: ⚙ 기능개발, 🚧 리팩토링

#73 [DF-69]북마크에 산책로 저장
  src/apis/bookmark.ts
  src/components/bottomsheet/BookmarkContent.tsx
Labels: ⚙ 기능개발

#76 fix(DF-55): 하트토글 및 api연동 수정
  src/apis/likedWalkway.type.ts
  src/apis/walkway.type.ts
  src/pages/detail/index.tsx
  src/pages/main/index.tsx
Labels: 🐞 버그

#78 [DF-92] [QA] 산책 종료 과정 개선과 모달 디자인 업데이트
  src/components/modal/ConfirmationModal.tsx
  src/pages/newway/index.tsx
Labels: 🐞 버그, 💎UI 개발

#80 [QA] 리뷰컴포넌트 수정 및 토스트 추가
  src/components/TrailReviewCard.tsx
  src/components/bottomsheet/BookmarkContent.tsx
  src/pages/detail/index.tsx
  src/pages/mypage/TrailReviewPage.tsx
  src/pages/mypage/index.tsx
Labels: 🐞 버그, ⚙ 기능개발
