Repository DongSanOfficial/DongSan-Front, pull requests merged in 2025-04, with the labels that each got.

#96 [DF-104] 계정 삭제 모달 및 api연결
  src/components/modal/ConfirmationModal.tsx
  src/pages/mypage/index.tsx
Labels: 💎UI 개발

#101 [DF-107] 바텀시트 컴포넌트 로직 변경
  src/assets/svg/Logout.svg
  src/components/appBar/index.tsx
  src/components/bottomNavigation/index.tsx
  src/components/bottomsheet/BottomSheet.tsx
  src/pages/detail/index.tsx
  src/pages/main/header/BottomSheetHeader.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
Labels: 🐞 버그

#102 [DF-109] 동산에 등록된 모든 산책로 조회
  src/apis/walkway.ts
  src/apis/walkway.type.ts
  src/pages/main/header/BottomSheetHeader.tsx
  src/pages/main/index.tsx
Labels: ⚙ 기능개발

#103 [DF-106] 애플 로그인 추가
  src/assets/svg/loginApple.png
  src/assets/svg/loginApple.svg
  src/components/button/LoginButton.tsx
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/styles/colors/theme.ts
Labels: ⚙ 기능개발, 💎UI 개발

#107 [DF-111] 북마크 타이틀 조회 api 연동
  src/apis/bookmark.ts
  src/apis/bookmark.type.ts
  src/pages/detail/bookmark/components/BookmarkContent.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/trailList/TrailListPage.tsx
Labels: ⚙ 기능개발
