Repository DongSanOfficial/DongSan-Front, pull requests merged in 2025-01, with the labels that each got.

#30 [DF-43] 쿠키 전송 허용
  src/pages/review/index.tsx
Labels: 🐞 버그

#31 마이페이지 유저 정보 조회 api 연동
  src/apis/api.type.ts
  src/apis/auth.ts
  src/apis/auth.type.ts
  src/apis/instance.ts
  src/pages/mypage/index.tsx
Labels: ⚙ 기능개발

#32 [DF-44] 작성한 리뷰 전체보기
  src/apis/review.ts
  src/apis/review.type.ts
  src/components/TrailReviewCard.tsx
  src/pages/mypage/TrailReviewPage.tsx
Labels: ⚙ 기능개발

#36 [DF-63]산책로 리뷰 별점보기 api 연동
  src/apis/review.ts
  src/apis/review.type.ts
  src/pages/index.tsx
  src/pages/review/ReviewCheck.tsx
Labels: ⚙ 기능개발

#37 [DF-65] 바텀시트 로직 수정 및 현재 위치 업데이트 기능 추가
  src/assets/svg/LocationIcon.svg
  src/assets/svg/RegisteredLocation.svg
  src/assets/svg/UserLocation.svg
  src/components/bottomsheet/BottomSheet.tsx
  src/components/map/MainMap.tsx
  src/pages/main/components/PathCard.tsx
  src/pages/main/index.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#41 [DF-64]산책로 리뷰 내용보기 api 연동
  src/apis/review.ts
  src/apis/review.type.ts
  src/pages/review/ReviewCheck.tsx
Labels: ⚙ 기능개발

#42 기획 수정사항 반영 (메인 페이지 디자인, 키워드 기반 검색 기능 추가)
  public/index.html
  src/assets/svg/DongSanTextLogo.svg
  src/assets/svg/FootPrint.svg
  src/components/BottomNav.tsx
  src/components/CommonDropdown.tsx
  src/components/bottomsheet/BottomSheet.tsx
  src/components/button/DropDownButton.tsx
  src/components/map/MainMap.tsx
  src/pages/main/components/PathCard.tsx
  src/pages/main/components/SearchResult.tsx
  src/pages/main/header/BottomSheetHeader.tsx
  src/pages/main/header/components/SearchInput.tsx
  src/pages/main/header/components/SortDropdown.tsx
  src/pages/main/index.tsx
  src/styles/colors/theme.ts
Labels: ⚙ 기능개발, 💎UI 개발

#43 [DF-71] 산책 경로 이미지화 및 폴리라인 지도 컴포넌트 구현
  src/components/map/PathMap.tsx
  src/components/map/TrackingMap.tsx
  src/components/newway_register/DateDisplay.tsx
  src/pages/newway/index.tsx
  src/pages/newway/registration.tsx
  src/utils/drawPathUtils.ts
Labels: ⚙ 기능개발

#44 로그인 페이지 리팩토링
  src/assets/svg/loginNaver.svg
  src/components/button/LoginButton.tsx
  src/constants/.gitkeep
  src/constants/develop.constants.ts
  src/navigator/CustomNavigator.tsx
  src/pages/main/index.tsx
  src/pages/signin/index.tsx
  src/styles/BottomBarLayout.tsx
  src/styles/colors/theme.ts
Labels: 💎UI 개발

#46 산책로 등록 페이지 완성
  src/components/map/PathMap.tsx
  src/components/myregister/index.tsx
  src/components/newway_register/InputField.tsx
  src/pages/newway/registration.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#48 [DF-73] 헤더, 바텀네비게이션 분리
  src/App.tsx
  src/components/Header.tsx
  src/components/appBar/index.tsx
  src/components/bottomNavigation/index.tsx
  src/components/bottomsheet/BottomSheet.tsx
  src/components/modal/Modal.tsx
  src/components/myregister/index.tsx
  src/navigator/CustomNavigator.tsx
  src/navigator/Navigator.tsx
  src/navigator/routes.tsx
  src/pages/detailpage/TrailLiked.tsx
  src/pages/detailpage/recommend_trail.tsx
  src/pages/main/components/SearchResult.tsx
  src/pages/main/index.tsx
  src/pages/mypage/TrailListLikePage.tsx
  src/pages/mypage/TrailListPage.tsx
  src/pages/mypage/TrailReviewPage.tsx
  src/pages/mypage/index.tsx
  src/pages/newway/index.tsx
  src/pages/newway/registration.tsx
  src/pages/review/ReviewCheck.tsx
  src/pages/review/index.tsx
  src/pages/usingtrail/detail_using.tsx
  src/pages/usingtrail/index.tsx
  src/styles/BottomBarLayout.tsx
Labels: 🐞 버그

#50 [DF-75] 트래킹 맵 test 페이지
  src/components/map/TrackingMapTest.tsx
  src/hooks/useWatchLocation.ts
  src/navigator/routes.tsx
  src/pages/newway/NewwayTest.tsx
  src/utils/calculateDistance.ts
Labels: 🐞 버그
